// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type StatementsTableRow = {
    id: string;
    name: string;
    type: "PG" | "R" | "TF";
    answers: json;
    statementsGroup1: { nodes: StatementsGroup1TableRow[] };
  };

  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    username: string;
    password: string;
    birthDate: Date;
    domicile: string;
    status: boolean;
    cardVerify: string;
    numberVerify: string;
  };

  type OutputsTableRow = {
    id: string;
    name: string;
    typeTestId: { nodes: TypeTestIdTableRow[] };
    description: string;
    outputTest1: { nodes: OutputTest1TableRow[] };
  };

  type SubmissionTableRow = {
    id: string;
    contributor: string;
    message: string;
    test: TestTableRow;
    date: Date;
    status: "waiting" | "approved" | "rejected" | "done";
    data: string;
    result: string;
  };

  type ProductsTableRow = {
    id: string;
    name: string;
    description: string;
    majors: string;
    test: { nodes: TestTableRow[] };
  };

  type TypesTableRow = {
    id: string;
    name: string;
    description: string;
    outputs: { nodes: OutputsTableRow[] };
    test1: { nodes: Test1TableRow[] };
  };

  type ArticleTableRow = {
    id: string;
    name: string;
    description: string;
  };

  type TestTableRow = {
    id: string;
    name: string;
    description: string;
    productId: { nodes: ProductIdTableRow[] };
    testType: TestTypeTableRow;
    type: string;
    outputTest: { nodes: OutputTestTableRow[] };
    statementsGroup: { nodes: StatementsGroupTableRow[] };
    test: { nodes: TestTableRow[] };
  };

  type OutputTestTableRow = {
    id: string;
    name: string;
    testId: TestIdTableRow;
    res: string;
    outputId: OutputIdTableRow;
  };

  type StatementsGroupTableRow = {
    id: string;
    name: string;
    testId: TestIdTableRow;
    statements: { nodes: StatementsTableRow[] };
  };

  type AuthDataViewRow = {
    read: {
      id: string;
      email: string;
      username: string;
      password: string;
      birthDate: Date;
      role: { id: string; displayField: string };
    };
    write: {
      email: string;
      username: string;
      password: string;
      birthDate: Date;
    };
    params: {};
    actions: {};
    forms: {
      createUser: {
        email?: string;
        role?: string;
        username?: string;
        password?: string;
        birthDate?: Date;
        domicile?: string;
        status?: boolean;
        cardVerify?: string;
        numberVerify?: string;
      };
      createAdmin: {
        email?: string;
        role?: string;
        username?: string;
        password?: string;
        birthDate?: Date;
        domicile?: string;
        status?: boolean;
        cardVerify?: string;
        numberVerify?: string;
      };
    };
  };

  type AllProductsViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      majors: string;
    };
    write: {
      name: string;
      description: string;
      majors: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllTypesViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllOutputsViewRow = {
    read: {
      id: string;
      name: string;
      typeTestId: { nodes: TypeTestIdTableRow[] };
      description: string;
    };
    write: {
      name: string;
      typeTestId: string[];
      description: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllStatementsViewRow = {
    read: {
      id: string;
      name: string;
      type: "PG" | "R" | "TF";
      answers: json;
    };
    write: {
      name: string;
      type: "PG" | "R" | "TF";
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllTestViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      productId: { nodes: ProductIdTableRow[] };
      testType: TestTypeTableRow;
      type: string;
    };
    write: {
      name: string;
      description: string;
      productId: string[];
      testType: string[];
      type: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllOutputTestViewRow = {
    read: {
      id: string;
      name: string;
      testId: TestIdTableRow;
      res: string;
      outputId: OutputIdTableRow;
    };
    write: {
      name: string;
      testId: string[];
      res: string;
      outputId: string[];
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllStatementsGroupViewRow = {
    read: {
      id: string;
      name: string;
      testId: TestIdTableRow;
      statements: { nodes: StatementsTableRow[] };
    };
    write: {
      name: string;
      testId: string[];
      statements: string[];
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      username: string;
      password: string;
      birthDate: Date;
      domicile: string;
      status: boolean;
      cardVerify: string;
      numberVerify: string;
    };
    write: {
      email: string;
      username: string;
      password: string;
      birthDate: Date;
      domicile: string;
      status: boolean;
      cardVerify: string;
      numberVerify: string;
    };
    params: {
      "$by.email"?: "asc";
    };
    actions: {};
    forms: {
      createUser: {
        email?: string;
        role?: string;
        username?: string;
        password?: string;
        birthDate?: Date;
        domicile?: string;
        status?: boolean;
        cardVerify?: string;
        numberVerify?: string;
      };
      createAdmin: {
        email?: string;
        role?: string;
        username?: string;
        password?: string;
        birthDate?: Date;
        domicile?: string;
        status?: boolean;
        cardVerify?: string;
        numberVerify?: string;
      };
    };
  };

  type AllArticleViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllSubmissionViewRow = {
    read: {
      id: string;
      contributor: string;
      message: string;
      test: TestTableRow;
      date: Date;
      status: "waiting" | "approved" | "rejected" | "done";
      data: string;
      result: string;
    };
    write: {
      contributor: string;
      message: string;
      test: string[];
      date: Date;
      status: "waiting" | "approved" | "rejected" | "done";
      data: string;
      result: string;
    };
    params: {
      "$by.contributor"?: "desc";
    };
    actions: {};
    forms: {
      addSubmision: {
        contributor?: string;
        message?: string;
        test?: string[];
        date?: Date;
        status?: "waiting" | "approved" | "rejected" | "done";
      };
    };
  };

  type ProjectSchema = {
    authData: AuthDataViewRow;
    allProducts: AllProductsViewRow;
    allTypes: AllTypesViewRow;
    allOutputs: AllOutputsViewRow;
    allStatements: AllStatementsViewRow;
    allTest: AllTestViewRow;
    allOutputTest: AllOutputTestViewRow;
    allStatementsGroup: AllStatementsGroupViewRow;
    allMember: AllMemberViewRow;
    allArticle: AllArticleViewRow;
    allSubmission: AllSubmissionViewRow;
  };
}
